services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./olivetin/config:/config
      - ./olivetin/keys:/home/olivetin/.ssh
    ports:
      - "80:1337"
    restart: unless-stopped

  lichtblick:
    container_name: lichtblick
    image: ghcr.io/lichtblick-suite/lichtblick:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  sshwifty:
    container_name: sshwifty
    image: niruix/sshwifty:latest
    ports:
      - "8182:8182"
    restart: unless-stopped
