services:
  olivetin:
    container_name: olivetin
    image: jamesread/olivetin
    volumes:
      - ./olivetin:/
    ports:
      - "80:1337"
    restart: unless-stopped

 lichtblick:
   image: ghcr.io/lichtblick-suite/lichtblick:latest
   ports:
     - "8080:8080"
   restart: unless-stopped
