listenAddressSingleHTTPFrontend: 0.0.0.0:1337
logLevel: "INFO"
pageTitle: fishwrap
insecureAllowDumpSos: true
showFooter: false
sectionNavigationStyle: topbar
showNavigation: false

actions:
  - title: Reboot Robot Computer
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo reboot'
    icon: restart
    popupOnStart: default
    arguments:
      - type: confirmation
        title: Confirm?
  
  - title: Shutdown Robot Computer
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo shutdown 0'
    icon: "&#128680;"
    popupOnStart: default
    arguments:
      - type: confirmation
        title: Confirm?

  - title: Kill and Delete ROS Container
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'docker rm -f steelhead-sbc'
    icon: "&#9940;"
    popupOnStart: execution-dialog
    arguments:
      - type: confirmation
        title: Confirm?

  - title: List Docker Containers
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'docker ps -a'
    icon: "&#128230;"
    popupOnStart: execution-dialog

  - title: List Docker Images
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'docker image ls'
    icon: "&#128230;"
    popupOnStart: execution-dialog

  - title: Download latest ROS Container
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'docker pull ghcr.io/ubc-subbots/steelhead-sbc:latest'
    icon: "&#128259;"
    timeout: 1200
    popupOnStart: execution-dialog

  - title: Start ROS Container
    shell: |
      #!/bin/bash
      ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 '
        if [ -n "$(sudo docker ps --filter 'name=^steelhead-sbc$' --filter 'status=running' --quiet)" ]; then
          echo "Container already running."
          exit 0
        fi
        sudo docker run -d \
          --name steelhead-sbc \
          --net=host \
          -v /dev:/dev \
          --privileged \
          ghcr.io/ubc-subbots/steelhead-sbc \
          tail -f /dev/null
      '
    icon: "&#128640;"
    timeout: 60
    popupOnStart: execution-dialog

  - title: Start Rosbridge WebSocket
    shell: |
      ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo docker exec -d steelhead-sbc bash -lc "
        source /root/steelhead/install/setup.bash &&
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml
      "'
    icon: "&#128268;"
    timeout: 15
    popupOnStart: execution-dialog

  - title: Initialize Listeners and Topics
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo docker exec -d steelhead-sbc bash -lc "
          source /root/steelhead/install/setup.bash &&
          ros2 launch steelhead_bringup pool_test_base_launch.py
        "'
    icon: "&#128161;"
    timeout: 40
    popupOnStart: execution-dialog

  - title: Configure PID Controller Parameters
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo docker exec -d steelhead-sbc bash -lc "
          source /root/steelhead/install/setup.bash &&
          ros2 param set /steelhead/controls/steelhead_pid_controller force_{{ dimension }}_{{ element }} {{ value }}
        "'
    icon: "&#128295;"
    timeout: 40
    arguments:
      - name: dimension
        description: Choose dimension
        choices:
          - title: X
            value: x

          - title: Y
            value: y

          - title: Z
            value: z

          - title: Pitch
            value: pitch

          - title: Roll
            value: roll

          - title: Yaw
            value: yaw
      - name: element
        description: Choose Element - Proportional (P), Integral (I), Derivative (D)
        choices:
          - title: Proportional (P)
            value: p

          - title: Integral (I)
            value: i

          - title: Derivative (D)
            value: d
      - name: value
        default: "0.0"
        type: ascii_sentence
    popupOnStart: execution-dialog

  - title: Configure autorun launch file
    icon: "&#128736;"
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sed -Ei "
          /ros2/c\  ros2 launch {{ PACKAGE }} {{ LAUNCHFILE }}" /home/subbots/fishwrap/olivetin/autostart.sh'
    arguments:
      - name: PACKAGE
        type: ascii_identifier
        title: Package name
        suggestions:
          - steelhead_bringup:
      - name: LAUNCHFILE
        type: ascii_identifier
        title: Launchfile name
        suggestions:
          - pool_test_hardcode_launch.py:

  - title: Enable/Disable - Autorun ROS launch file on computer bootup
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo systemctl {{ newStatus }} steelhead-autolaunch.service --no-pager
        '
    icon: "&#128295;"
    timeout: 10
    arguments:
      - name: newStatus
        description: What to do to on-boot routine?
        choices:
          - title: Enable
            value: enable

          - title: Disable
            value: disable

          - title: Query Status
            value: is-enabled
    popupOnStart: execution-dialog

  - title: Run autorun launch file NOW
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 '/home/subbots/fishwrap/olivetin/autostart.sh
        '
    icon: "&#129349;"
    timeout: 30
    popupOnStart: execution-dialog

  - title: All-thruster Test
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo docker exec -d steelhead-sbc bash -lc "
          source /root/steelhead/install/setup.bash &&
          ros2 topic pub /motor_control std_msgs/msg/UInt32 \"data: 0b00100011000110001100011000110001\"
        "'
    icon: "&#127946;"
    timeout: 40
    popupOnStart: execution-dialog

  - title: All-thruster Stop
    shell: |
        ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'sudo docker exec -d steelhead-sbc bash -lc "
          source /root/steelhead/install/setup.bash &&
          ros2 topic pub /motor_control std_msgs/msg/UInt32 \"data: 0b00100001000010000100001000010000\"
        "'
    icon: "&#128721;"
    timeout: 40
    popupOnStart: execution-dialog
  
  - title: Ping Internet
    shell: ping -c 4 1.0.0.1
    timeout: 15
    icon: ping
    popupOnStart: execution-dialog-stdout-only
  
  - title: Ping Router
    shell: ping -c 4 10.42.0.2
    timeout: 15
    icon: ping
    popupOnStart: execution-dialog-stdout-only

  - title: Get Host Network Config
    shell: ssh -o StrictHostKeyChecking=no subbots@172.17.0.1 'ip a'
    icon: "&#128732;"
    popupOnStart: execution-dialog-stdout-only
  

dashboards:
  - title: Robot Dashboard
    contents:
      - title: 1. ROS Container Actions
        type: fieldset
        contents:
          - title: Download latest ROS Container
          - title: Kill and Delete ROS Container
          - title: Start ROS Container
          - title: Initialize Listeners and Topics
          - title: Start Rosbridge WebSocket
          - title: Configure autorun launch file
          - title: Enable/Disable - Autorun ROS launch file on computer bootup
          - title: Run autorun launch file NOW
          - title: Configure PID Controller Parameters
          - title: All-thruster Test
          - title: All-thruster Stop
      - title: 2. Computer Actions
        type: fieldset
        contents:
          - title: List Docker Containers
          - title: List Docker Images
          - title: Ping Internet
          - title: Ping Router
          - title: Get Host Network Config
      - title: 3. Links
        type: fieldset
        contents:
          - type: display
            title: |
              <a href="http://10.42.0.3:81" target="_blank" rel="noopener noreferrer">Lichtblick (teleop and topic visualization) (Wi-Fi)</a>
          - type: display
            title: |
              <a href="http://10.42.0.3:82/?hostname=10.42.0.3&username=subbots&password=c3ViYm90cw" target="_blank" rel="noopener noreferrer">Web Terminal (Wi-Fi)</a>
          - type: display
            title: |
              <a href="http://10.42.0.4:81" target="_blank" rel="noopener noreferrer">Lichtblick (teleop and topic visualization) (Ethernet/Tether)</a>
          - type: display
            title: |
              <a href="http://10.42.0.4:82/?hostname=10.42.0.4&username=subbots&password=c3ViYm90cw" target="_blank" rel="noopener noreferrer">Web Terminal (Ethernet/Tether)</a>
      - title: 4. DANGER ZONE
        type: fieldset
        contents:
          - title: Reboot Robot Computer
          - title: Shutdown Robot Computer
